### PR TITLE
First version of CI workflow created

### LINKED ISSUE #3: Set up CI workflow

### PR DESCRIPTION
**Pull request by yvesbou**
I created a first draft of the CI workflow but I want to include the job "push_to_vercel", since you @LinusWeigand  deployed it to Vercel, you might have the following information:

```
vercel-token: ${{ secrets.VERCEL_TOKEN }}
vercel-org-id: ${{ secrets.ORG_ID}} 
vercel-project-id: ${{ secrets.PROJECT_ID}}
vercel-args: "--prod"
```

### CODE REVIEW

**Comment by yvesbou** [comment]
@leovct how did you add the 2 approvals which are needed?

**Comment by leovct** [comment]
It's in the settings of the repo, under `branches`, click on `add rule`.

**Review by leovct — DISMISSED** [review]

**Comment by leovct** [comment]
Hi @yvesbou, could you update the ci workflow to stick to what has been done in the smart contract repository?

- [x] CI workflow should be triggered on every branches (and not only on the main branch).
- [x] The current node workflow tests how our app behaves on node 12.x, 14.x and 16.x. I think this is not necessary since our app will only run on a node 16.x environment. What I suggest is to only test the app on this environment and remove the matrix tests.

**Review by leovct — COMMENTED** [review]
looks good to me! 😀

**Review by leovct — DISMISSED** [review]

**Comment by yvesbou** [comment]
updated package-lock.json and yarn.lock after updating Browserslist (caniuse-lite is outdated) with `npx browserslist@latest --update-db`

```
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```

**Comment by yvesbou** [comment]
`npm run test --if-present` did not work 

```
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
```

**Comment by yvesbou** [comment]
`npm test --passWithNoTests`

same result as with `npm run test --if-present`:
```
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
```

**Review by leovct — APPROVED** [review]

**Pull request merged**
